/**
 * Emoji library, grouped by the job the emoji is doing in a post rather than by
 * Unicode category — you reach for "a bullet that signals growth", not "plant life".
 *
 * Note on GIFs: LinkedIn post bodies are plain text. GIFs work in comments and
 * direct messages, and can be attached to a post as media, but nothing can embed
 * one inside the text itself. Emoji are the only inline visual that survives.
 *
 * `k` holds search keywords. Every entry renders on iOS, Android, Windows and
 * macOS; nothing here is a recent addition that would show as a blank box on
 * older devices.
 */

export const CATEGORIES = [
  {
    id: 'popular',
    name: 'Most used',
    hint: 'The ones that actually show up in high-performing posts.',
    items: [
      { c: '🚀', k: 'rocket launch growth ship startup' },
      { c: '💡', k: 'idea lightbulb insight tip' },
      { c: '✅', k: 'check tick done complete yes' },
      { c: '👉', k: 'point right arrow cta' },
      { c: '🔥', k: 'fire hot popular trending' },
      { c: '📈', k: 'chart up growth increase revenue' },
      { c: '🎯', k: 'target goal aim focus objective' },
      { c: '⚡', k: 'lightning fast energy speed' },
      { c: '💪', k: 'strong muscle effort resilience' },
      { c: '🙏', k: 'thanks grateful please pray' },
      { c: '👏', k: 'clap applause congrats well done' },
      { c: '🤔', k: 'thinking question consider hmm' },
      { c: '❤️', k: 'heart love care' },
      { c: '⭐', k: 'star favourite rating quality' },
      { c: '📌', k: 'pin important save note' },
      { c: '🧠', k: 'brain smart thinking learning' },
      { c: '⏰', k: 'clock time deadline urgent' },
      { c: '🎉', k: 'party celebrate launch congrats' },
      { c: '💬', k: 'comment speech discuss reply' },
      { c: '🔑', k: 'key insight important unlock' },
    ],
  },
  {
    id: 'growth',
    name: 'Growth & data',
    hint: 'For metrics, results and anything with a number attached.',
    items: [
      { c: '📈', k: 'chart increasing growth up revenue' },
      { c: '📉', k: 'chart decreasing decline down loss' },
      { c: '📊', k: 'bar chart data analytics metrics' },
      { c: '💹', k: 'chart yen market finance growth' },
      { c: '🏆', k: 'trophy win award first place' },
      { c: '🥇', k: 'gold medal first winner' },
      { c: '🥈', k: 'silver medal second' },
      { c: '🥉', k: 'bronze medal third' },
      { c: '🎖️', k: 'medal honour achievement' },
      { c: '💰', k: 'money bag revenue funding profit' },
      { c: '💵', k: 'dollar cash money price' },
      { c: '💸', k: 'money flying spend burn cost' },
      { c: '🪙', k: 'coin money token' },
      { c: '📶', k: 'signal bars strength growth' },
      { c: '🔢', k: 'numbers count data' },
      { c: '➕', k: 'plus add increase more' },
      { c: '➖', k: 'minus subtract less decrease' },
      { c: '✖️', k: 'multiply times x' },
      { c: '💯', k: 'hundred percent full score perfect' },
      { c: '📐', k: 'ruler measure precision' },
    ],
  },
  {
    id: 'work',
    name: 'Work & tools',
    hint: 'Objects that stand in for a job, a task or a workplace.',
    items: [
      { c: '💼', k: 'briefcase business job work career' },
      { c: '🏢', k: 'office building company corporate' },
      { c: '🏗️', k: 'construction building crane wip' },
      { c: '🛠️', k: 'tools build fix engineering' },
      { c: '🔧', k: 'wrench fix repair tool' },
      { c: '⚙️', k: 'gear settings process ops system' },
      { c: '🔨', k: 'hammer build make' },
      { c: '📋', k: 'clipboard list tasks checklist' },
      { c: '📝', k: 'memo write note draft' },
      { c: '✍️', k: 'writing hand author sign' },
      { c: '📄', k: 'document page file report' },
      { c: '📁', k: 'folder files organise' },
      { c: '📅', k: 'calendar date schedule' },
      { c: '🗓️', k: 'calendar spiral planning schedule' },
      { c: '📎', k: 'paperclip attach link' },
      { c: '🖇️', k: 'paperclips attach group' },
      { c: '✂️', k: 'scissors cut trim reduce' },
      { c: '📢', k: 'announce loudspeaker news shout' },
      { c: '📣', k: 'megaphone announce marketing promote' },
      { c: '🔔', k: 'bell alert notify reminder' },
      { c: '🗂️', k: 'dividers organise category' },
      { c: '📦', k: 'package box ship delivery product' },
      { c: '🏷️', k: 'label tag price category' },
      { c: '🔍', k: 'search magnify find research' },
      { c: '🔎', k: 'search magnify right find' },
      { c: '⌛', k: 'hourglass time waiting deadline' },
      { c: '⏳', k: 'hourglass flowing time running out' },
      { c: '📞', k: 'phone call contact' },
      { c: '📧', k: 'email mail message contact' },
      { c: '🖊️', k: 'pen write sign' },
    ],
  },
  {
    id: 'tech',
    name: 'Tech & product',
    hint: 'For engineering, product and anything shipped.',
    items: [
      { c: '💻', k: 'laptop computer code work remote' },
      { c: '🖥️', k: 'desktop computer monitor' },
      { c: '⌨️', k: 'keyboard typing code' },
      { c: '🖱️', k: 'mouse click computer' },
      { c: '📱', k: 'phone mobile app device' },
      { c: '🤖', k: 'robot ai automation bot' },
      { c: '🛜', k: 'wireless wifi network' },
      { c: '🔌', k: 'plug integration connect power' },
      { c: '🔋', k: 'battery power energy charge' },
      { c: '💾', k: 'floppy save disk data legacy' },
      { c: '💿', k: 'disc cd data storage' },
      { c: '🗄️', k: 'file cabinet database storage archive' },
      { c: '🖨️', k: 'printer print output' },
      { c: '📡', k: 'satellite signal broadcast network' },
      { c: '🔐', k: 'lock key security encrypted' },
      { c: '🔒', k: 'lock closed secure private' },
      { c: '🔓', k: 'lock open unlocked access' },
      { c: '🛡️', k: 'shield security protect defence' },
      { c: '🐛', k: 'bug defect issue error' },
      { c: '🧪', k: 'test tube experiment testing beta' },
      { c: '🔬', k: 'microscope research analysis detail' },
      { c: '⚗️', k: 'alembic experiment chemistry research' },
      { c: '🧬', k: 'dna science research biotech' },
      { c: '🕹️', k: 'joystick game control' },
    ],
  },
  {
    id: 'people',
    name: 'People & gestures',
    hint: 'Hands point, invite and emphasise. Use them as bullets sparingly.',
    items: [
      { c: '👉', k: 'point right cta direction' },
      { c: '👈', k: 'point left back' },
      { c: '👇', k: 'point down below comments link' },
      { c: '👆', k: 'point up above' },
      { c: '👏', k: 'clap applause congratulations' },
      { c: '🙌', k: 'raised hands celebrate praise' },
      { c: '🤝', k: 'handshake deal partnership agreement' },
      { c: '👋', k: 'wave hello goodbye greeting' },
      { c: '💪', k: 'muscle strong effort resilience' },
      { c: '🙏', k: 'thanks grateful pray please' },
      { c: '👍', k: 'thumbs up good agree yes like' },
      { c: '👎', k: 'thumbs down bad disagree no' },
      { c: '✊', k: 'fist solidarity power' },
      { c: '🤞', k: 'fingers crossed hope luck' },
      { c: '🫡', k: 'salute respect acknowledge yes' },
      { c: '🤲', k: 'open hands offer give' },
      { c: '🧑‍💻', k: 'person computer developer engineer' },
      { c: '👩‍💻', k: 'woman computer developer engineer' },
      { c: '👨‍💻', k: 'man computer developer engineer' },
      { c: '🧑‍🏫', k: 'teacher educator mentor training' },
      { c: '🧑‍🔬', k: 'scientist researcher' },
      { c: '🧑‍🚀', k: 'astronaut explorer ambitious' },
      { c: '👥', k: 'people team group users' },
      { c: '👤', k: 'person user profile individual' },
      { c: '🗣️', k: 'speaking head voice speak advocate' },
      { c: '🫂', k: 'hug support community care' },
    ],
  },
  {
    id: 'faces',
    name: 'Faces',
    hint: 'Tone markers. One is plenty; a row of them reads as noise.',
    items: [
      { c: '🙂', k: 'slight smile friendly' },
      { c: '😊', k: 'smile happy warm pleased' },
      { c: '😀', k: 'grin happy cheerful' },
      { c: '😅', k: 'sweat smile awkward relief nervous' },
      { c: '😂', k: 'laugh tears funny joke' },
      { c: '🤣', k: 'rolling laughing hilarious' },
      { c: '😉', k: 'wink joke playful' },
      { c: '🤔', k: 'thinking consider question hmm' },
      { c: '🤨', k: 'raised eyebrow sceptical doubt' },
      { c: '😐', k: 'neutral flat deadpan' },
      { c: '😬', k: 'grimace awkward cringe yikes' },
      { c: '🙃', k: 'upside down irony sarcasm' },
      { c: '😮', k: 'surprised shock wow' },
      { c: '🤯', k: 'mind blown shock amazed' },
      { c: '😴', k: 'sleep tired boring' },
      { c: '🥲', k: 'smile tear bittersweet proud' },
      { c: '🥹', k: 'holding back tears moved touched' },
      { c: '😎', k: 'sunglasses cool confident' },
      { c: '🤓', k: 'nerd glasses technical detail' },
      { c: '🫠', k: 'melting overwhelmed burnout' },
      { c: '😤', k: 'determined frustrated steam' },
      { c: '🥳', k: 'party face celebrate congrats' },
    ],
  },
  {
    id: 'marks',
    name: 'Marks & bullets',
    hint: 'The workhorses. These make lists scannable without shouting.',
    items: [
      { c: '✅', k: 'check green tick done yes complete' },
      { c: '☑️', k: 'checkbox ticked done' },
      { c: '✔️', k: 'check mark tick done' },
      { c: '❌', k: 'cross wrong no error fail' },
      { c: '❎', k: 'cross green negative no' },
      { c: '⛔', k: 'no entry stop forbidden' },
      { c: '🚫', k: 'prohibited banned no' },
      { c: '⚠️', k: 'warning caution careful risk' },
      { c: '❗', k: 'exclamation important urgent' },
      { c: '❓', k: 'question ask unknown' },
      { c: '💠', k: 'diamond bullet decorative' },
      { c: '🔹', k: 'small blue diamond bullet' },
      { c: '🔸', k: 'small orange diamond bullet' },
      { c: '🔷', k: 'large blue diamond bullet' },
      { c: '🔶', k: 'large orange diamond bullet' },
      { c: '▪️', k: 'small black square bullet' },
      { c: '▫️', k: 'small white square bullet' },
      { c: '◾', k: 'medium black square bullet' },
      { c: '🔺', k: 'red triangle up increase' },
      { c: '🔻', k: 'red triangle down decrease' },
      { c: '🟢', k: 'green circle good status go' },
      { c: '🟡', k: 'yellow circle warning caution' },
      { c: '🔴', k: 'red circle bad stop alert' },
      { c: '🟣', k: 'purple circle status' },
      { c: '🔵', k: 'blue circle status' },
      { c: '⚫', k: 'black circle bullet' },
      { c: '⚪', k: 'white circle bullet empty' },
    ],
  },
  {
    id: 'arrows',
    name: 'Arrows & flow',
    hint: 'For before/after, steps and cause-and-effect.',
    items: [
      { c: '➡️', k: 'right arrow next then leads to' },
      { c: '⬅️', k: 'left arrow back previous' },
      { c: '⬆️', k: 'up arrow increase rise' },
      { c: '⬇️', k: 'down arrow decrease fall' },
      { c: '↗️', k: 'up right arrow growth trending' },
      { c: '↘️', k: 'down right arrow decline' },
      { c: '🔄', k: 'refresh cycle loop repeat iterate' },
      { c: '🔃', k: 'clockwise vertical reload' },
      { c: '🔁', k: 'repeat loop again' },
      { c: '⤴️', k: 'arrow curving up escalate' },
      { c: '⤵️', k: 'arrow curving down' },
      { c: '🔀', k: 'shuffle cross random' },
      { c: '⏩', k: 'fast forward speed skip' },
      { c: '▶️', k: 'play start begin' },
      { c: '⏸️', k: 'pause hold wait' },
      { c: '⏹️', k: 'stop end' },
      { c: '🔚', k: 'end finish conclusion' },
      { c: '🔜', k: 'soon coming next' },
      { c: '🆕', k: 'new fresh launch' },
      { c: '🆓', k: 'free no cost' },
    ],
  },
  {
    id: 'celebrate',
    name: 'Milestones',
    hint: 'New job, funding, launch, anniversary.',
    items: [
      { c: '🎉', k: 'party popper celebrate congrats launch' },
      { c: '🎊', k: 'confetti celebrate party' },
      { c: '🥳', k: 'partying face celebrate' },
      { c: '🎈', k: 'balloon celebrate anniversary' },
      { c: '🎂', k: 'cake birthday anniversary year' },
      { c: '🍾', k: 'champagne celebrate success toast' },
      { c: '🥂', k: 'cheers toast celebrate together' },
      { c: '🏅', k: 'medal award achievement' },
      { c: '🎁', k: 'gift present offer bonus' },
      { c: '✨', k: 'sparkles new shiny special magic' },
      { c: '🌟', k: 'glowing star standout excellence' },
      { c: '💫', k: 'dizzy sparkle magic' },
      { c: '🎓', k: 'graduation degree education learning' },
      { c: '📜', k: 'scroll certificate credential' },
      { c: '🔖', k: 'bookmark save milestone' },
      { c: '🎀', k: 'ribbon gift wrapped' },
    ],
  },
  {
    id: 'ideas',
    name: 'Ideas & learning',
    hint: 'Insight, education, books and thinking.',
    items: [
      { c: '💡', k: 'lightbulb idea insight tip' },
      { c: '🧠', k: 'brain thinking smart learning' },
      { c: '📚', k: 'books reading learning study' },
      { c: '📖', k: 'open book reading story' },
      { c: '🗞️', k: 'newspaper news press article' },
      { c: '📰', k: 'newspaper news press media' },
      { c: '🔖', k: 'bookmark save read later' },
      { c: '🧩', k: 'puzzle piece problem solving fit' },
      { c: '🗺️', k: 'map roadmap plan direction' },
      { c: '🧭', k: 'compass direction guidance strategy' },
      { c: '🔭', k: 'telescope vision future long term' },
      { c: '💭', k: 'thought bubble thinking reflection' },
      { c: '❔', k: 'question white curiosity' },
      { c: '📔', k: 'notebook journal notes' },
      { c: '🎨', k: 'art palette creative design' },
      { c: '🖌️', k: 'paintbrush design creative' },
    ],
  },
  {
    id: 'time',
    name: 'Time & place',
    hint: 'Deadlines, locations, remote work.',
    items: [
      { c: '⏰', k: 'alarm clock deadline urgent time' },
      { c: '🕐', k: 'clock one time hour' },
      { c: '📆', k: 'calendar date schedule tear off' },
      { c: '🗓️', k: 'calendar planning schedule' },
      { c: '🌍', k: 'globe europe africa world global' },
      { c: '🌎', k: 'globe americas world global' },
      { c: '🌏', k: 'globe asia australia world global' },
      { c: '🏠', k: 'house home remote wfh' },
      { c: '🏡', k: 'house garden home remote' },
      { c: '✈️', k: 'plane travel flight conference' },
      { c: '🚗', k: 'car commute drive travel' },
      { c: '🌆', k: 'city dusk urban office' },
      { c: '🌅', k: 'sunrise morning early start' },
      { c: '🌙', k: 'moon night late evening' },
      { c: '☕', k: 'coffee morning break chat' },
      { c: '🍵', k: 'tea break calm' },
    ],
  },
  {
    id: 'nature',
    name: 'Growth & nature',
    hint: 'Metaphors for building slowly and compounding.',
    items: [
      { c: '🌱', k: 'seedling growth start beginning new' },
      { c: '🌿', k: 'herb growth green sustainable' },
      { c: '🌳', k: 'tree growth mature established' },
      { c: '🌲', k: 'evergreen tree lasting' },
      { c: '🍃', k: 'leaves wind fresh light' },
      { c: '🌊', k: 'wave momentum flow change' },
      { c: '⛰️', k: 'mountain challenge climb goal' },
      { c: '🏔️', k: 'snow mountain peak summit' },
      { c: '🌤️', k: 'sun behind cloud optimism' },
      { c: '☀️', k: 'sun bright positive day' },
      { c: '🌈', k: 'rainbow hope diversity after storm' },
      { c: '⛈️', k: 'storm difficulty crisis turbulence' },
      { c: '❄️', k: 'snowflake unique cold freeze' },
      { c: '🔥', k: 'fire hot trending burnout intense' },
      { c: '💧', k: 'droplet water small drop' },
      { c: '🦋', k: 'butterfly transformation change' },
    ],
  },
];

/** Flat list, used by search. */
const ALL = CATEGORIES.flatMap((cat) =>
  cat.items.map((item) => ({ ...item, category: cat.id }))
);

/**
 * Matches on keywords; empty query returns nothing so the picker shows categories
 * instead. Results are deduplicated because some emoji are deliberately listed in
 * more than one category (📈 belongs in both "Most used" and "Growth"), and a
 * search result showing the same character twice just looks broken.
 */
export function searchEmoji(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  const seen = new Set();
  return ALL.filter((item) => {
    if (seen.has(item.c)) return false;
    if (!terms.every((t) => item.k.includes(t) || item.c === t)) return false;
    seen.add(item.c);
    return true;
  });
}

/** Distinct characters, which is the number worth showing a user. */
export const EMOJI_COUNT = new Set(ALL.map((i) => i.c)).size;
