/**
 * Symbol library.
 *
 * LinkedIn has no list markup, no rules, no blockquotes — every visual structure
 * in a post is a literal character someone pasted in. That makes the symbol set
 * the real formatting vocabulary of the platform, so this aims to be exhaustive
 * for the kinds people actually use rather than a token handful.
 *
 * Everything here is plain BMP text (no emoji presentation variants except where
 * marked), which is what survives LinkedIn's pipeline and renders across
 * Windows, macOS, iOS and Android without falling back to tofu.
 */

export const SYMBOL_GROUPS = [
  {
    id: 'bullets',
    name: 'Bullets',
    hint: 'Line starters. One consistent bullet reads better than a mix.',
    items: [
      { c: '•', k: 'bullet dot point round' },
      { c: '◦', k: 'bullet hollow small circle sub' },
      { c: '‣', k: 'bullet triangle point' },
      { c: '▪', k: 'bullet square small filled' },
      { c: '▫', k: 'bullet square small hollow' },
      { c: '■', k: 'square filled block' },
      { c: '□', k: 'square hollow empty box' },
      { c: '●', k: 'circle filled dot large' },
      { c: '○', k: 'circle hollow empty' },
      { c: '◆', k: 'diamond filled' },
      { c: '◇', k: 'diamond hollow' },
      { c: '▸', k: 'triangle right small play' },
      { c: '▹', k: 'triangle right hollow' },
      { c: '➤', k: 'arrow head bullet point' },
      { c: '➢', k: 'arrow head hollow bullet' },
      { c: '⁃', k: 'hyphen bullet dash' },
      { c: '–', k: 'en dash hyphen' },
      { c: '—', k: 'em dash long' },
      { c: '·', k: 'middle dot interpunct small' },
      { c: '⦿', k: 'circle target bullseye bullet' },
    ],
  },
  {
    id: 'checks',
    name: 'Checks & alerts',
    hint: 'Pros and cons, do and don’t, warnings.',
    items: [
      { c: '✅', k: 'check green tick done yes complete' },
      { c: '✔', k: 'check tick mark plain' },
      { c: '✓', k: 'check tick light' },
      { c: '☑', k: 'checkbox ticked done' },
      { c: '❌', k: 'cross red wrong no fail' },
      { c: '✗', k: 'cross x wrong plain' },
      { c: '✘', k: 'cross x heavy wrong' },
      { c: '❎', k: 'cross green negative' },
      { c: '☐', k: 'checkbox empty todo unchecked' },
      { c: '☒', k: 'checkbox crossed rejected' },
      { c: '⛔', k: 'no entry stop forbidden' },
      { c: '🚫', k: 'prohibited banned no' },
      { c: '⚠️', k: 'warning caution risk careful' },
      { c: '❗', k: 'exclamation important urgent' },
      { c: '❓', k: 'question ask unknown' },
      { c: '‼', k: 'double exclamation very important' },
      { c: '⁉', k: 'exclamation question surprise' },
      { c: '⚡', k: 'lightning fast energy' },
    ],
  },
  {
    id: 'arrows',
    name: 'Arrows',
    hint: 'Before and after, cause and effect, steps.',
    items: [
      { c: '→', k: 'right arrow leads to then' },
      { c: '←', k: 'left arrow back' },
      { c: '↑', k: 'up arrow increase rise' },
      { c: '↓', k: 'down arrow decrease fall' },
      { c: '↔', k: 'left right arrow both' },
      { c: '↕', k: 'up down arrow vertical' },
      { c: '⇒', k: 'double right arrow implies therefore' },
      { c: '⇐', k: 'double left arrow' },
      { c: '⇨', k: 'right arrow wide hollow' },
      { c: '➜', k: 'right arrow heavy' },
      { c: '➡️', k: 'right arrow emoji' },
      { c: '⬅️', k: 'left arrow emoji' },
      { c: '⬆️', k: 'up arrow emoji increase' },
      { c: '⬇️', k: 'down arrow emoji decrease' },
      { c: '↗', k: 'up right growth trending' },
      { c: '↘', k: 'down right decline' },
      { c: '↖', k: 'up left' },
      { c: '↙', k: 'down left' },
      { c: '⤴', k: 'curve up escalate' },
      { c: '⤵', k: 'curve down' },
      { c: '↻', k: 'rotate clockwise loop repeat' },
      { c: '↺', k: 'rotate anticlockwise undo' },
      { c: '⟶', k: 'long right arrow' },
      { c: '▶', k: 'play triangle right start' },
      { c: '◀', k: 'triangle left back' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    hint: 'Numbered lists. Emoji digits are boldest; circled ones are quieter.',
    items: [
      { c: '1️⃣', k: 'one 1 number emoji' },
      { c: '2️⃣', k: 'two 2 number emoji' },
      { c: '3️⃣', k: 'three 3 number emoji' },
      { c: '4️⃣', k: 'four 4 number emoji' },
      { c: '5️⃣', k: 'five 5 number emoji' },
      { c: '6️⃣', k: 'six 6 number emoji' },
      { c: '7️⃣', k: 'seven 7 number emoji' },
      { c: '8️⃣', k: 'eight 8 number emoji' },
      { c: '9️⃣', k: 'nine 9 number emoji' },
      { c: '🔟', k: 'ten 10 number emoji' },
      { c: '①', k: 'one 1 circled' },
      { c: '②', k: 'two 2 circled' },
      { c: '③', k: 'three 3 circled' },
      { c: '④', k: 'four 4 circled' },
      { c: '⑤', k: 'five 5 circled' },
      { c: '⑥', k: 'six 6 circled' },
      { c: '⑦', k: 'seven 7 circled' },
      { c: '⑧', k: 'eight 8 circled' },
      { c: '⑨', k: 'nine 9 circled' },
      { c: '⑩', k: 'ten 10 circled' },
      { c: 'Ⅰ', k: 'roman one 1' },
      { c: 'Ⅱ', k: 'roman two 2' },
      { c: 'Ⅲ', k: 'roman three 3' },
      { c: 'Ⅳ', k: 'roman four 4' },
      { c: 'Ⅴ', k: 'roman five 5' },
    ],
  },
  {
    id: 'dividers',
    name: 'Dividers',
    hint: 'Section breaks. One per post — more and it reads as decoration.',
    items: [
      { c: '━━━━━━━━━━', k: 'divider heavy line rule' },
      { c: '──────────', k: 'divider light line rule' },
      { c: '══════════', k: 'divider double line' },
      { c: '▬▬▬▬▬▬▬▬', k: 'divider thick bar block' },
      { c: '⎯⎯⎯⎯⎯⎯⎯⎯', k: 'divider thin line' },
      { c: '┈┈┈┈┈┈┈┈', k: 'divider dotted' },
      { c: '╌╌╌╌╌╌╌╌', k: 'divider dashed' },
      { c: '＿＿＿＿＿', k: 'divider underscore wide' },
      { c: '• • • • •', k: 'divider dots spaced' },
      { c: '✦ ✦ ✦', k: 'divider stars sparkle' },
      { c: '· · · · ·', k: 'divider small dots' },
      { c: '～～～～～', k: 'divider wave tilde' },
    ],
  },
  {
    id: 'stars',
    name: 'Stars & emphasis',
    hint: 'Ratings, highlights, standout points.',
    items: [
      { c: '★', k: 'star filled rating' },
      { c: '☆', k: 'star hollow empty rating' },
      { c: '⭐', k: 'star emoji favourite' },
      { c: '🌟', k: 'glowing star standout' },
      { c: '✨', k: 'sparkles new special' },
      { c: '✦', k: 'star four point sparkle' },
      { c: '✧', k: 'star four point hollow' },
      { c: '❖', k: 'diamond decorative' },
      { c: '❥', k: 'heart decorative' },
      { c: '♦', k: 'diamond suit' },
      { c: '♥', k: 'heart suit love' },
      { c: '☞', k: 'pointing hand right note' },
      { c: '☛', k: 'pointing hand right filled' },
      { c: '✱', k: 'asterisk star footnote' },
      { c: '❯', k: 'chevron right' },
      { c: '»', k: 'double chevron right more' },
      { c: '«', k: 'double chevron left' },
    ],
  },
  {
    id: 'progress',
    name: 'Bars & blocks',
    hint: 'Progress bars and simple charts. Build them by repeating a block.',
    items: [
      { c: '█', k: 'block full solid bar' },
      { c: '▓', k: 'block dark shade' },
      { c: '▒', k: 'block medium shade' },
      { c: '░', k: 'block light shade empty' },
      { c: '▰', k: 'bar filled segment' },
      { c: '▱', k: 'bar empty segment' },
      { c: '▮', k: 'bar vertical filled' },
      { c: '▯', k: 'bar vertical empty' },
      { c: '▪', k: 'small square filled' },
      { c: '█████░░░░░', k: 'progress bar 50 percent half' },
      { c: '███████░░░', k: 'progress bar 70 percent' },
      { c: '▰▰▰▰▱▱▱▱', k: 'progress segments half' },
    ],
  },
  {
    id: 'punctuation',
    name: 'Punctuation',
    hint: 'Typographic marks a plain keyboard will not give you.',
    items: [
      { c: '“', k: 'quote open curly left double' },
      { c: '”', k: 'quote close curly right double' },
      { c: '‘', k: 'quote open single curly' },
      { c: '’', k: 'apostrophe quote close single curly' },
      { c: '„', k: 'quote low double german' },
      { c: '…', k: 'ellipsis three dots' },
      { c: '–', k: 'en dash range' },
      { c: '—', k: 'em dash break' },
      { c: '§', k: 'section mark' },
      { c: '¶', k: 'paragraph pilcrow' },
      { c: '†', k: 'dagger footnote' },
      { c: '‡', k: 'double dagger footnote' },
      { c: '№', k: 'number sign numero' },
      { c: '‽', k: 'interrobang surprise question' },
      { c: '·', k: 'middle dot separator' },
      { c: '⁄', k: 'fraction slash' },
    ],
  },
  {
    id: 'math',
    name: 'Numbers & currency',
    hint: 'For metrics, prices and comparisons.',
    items: [
      { c: '%', k: 'percent' },
      { c: '‰', k: 'per mille thousand' },
      { c: '×', k: 'multiply times x' },
      { c: '÷', k: 'divide' },
      { c: '±', k: 'plus minus approximately' },
      { c: '≈', k: 'approximately roughly about' },
      { c: '≠', k: 'not equal different' },
      { c: '≤', k: 'less than or equal' },
      { c: '≥', k: 'greater than or equal' },
      { c: '∞', k: 'infinity endless' },
      { c: '√', k: 'square root' },
      { c: 'Δ', k: 'delta change difference' },
      { c: '°', k: 'degree temperature' },
      { c: '$', k: 'dollar usd money' },
      { c: '€', k: 'euro money' },
      { c: '£', k: 'pound sterling money' },
      { c: '¥', k: 'yen yuan money' },
      { c: '₹', k: 'rupee india money' },
      { c: '₽', k: 'rouble money' },
      { c: '¢', k: 'cent money' },
      { c: '™', k: 'trademark' },
      { c: '©', k: 'copyright' },
      { c: '®', k: 'registered trademark' },
    ],
  },
  {
    id: 'frames',
    name: 'Brackets & frames',
    hint: 'For labels and callouts, e.g. 【Update】.',
    items: [
      { c: '【', k: 'bracket heavy open label' },
      { c: '】', k: 'bracket heavy close label' },
      { c: '「', k: 'bracket corner open' },
      { c: '」', k: 'bracket corner close' },
      { c: '『', k: 'bracket white corner open' },
      { c: '』', k: 'bracket white corner close' },
      { c: '〈', k: 'angle bracket open' },
      { c: '〉', k: 'angle bracket close' },
      { c: '⟨', k: 'math angle bracket open' },
      { c: '⟩', k: 'math angle bracket close' },
      { c: '⌈', k: 'ceiling left corner' },
      { c: '⌉', k: 'ceiling right corner' },
      { c: '⌊', k: 'floor left corner' },
      { c: '⌋', k: 'floor right corner' },
      { c: '│', k: 'vertical line pipe' },
      { c: '┃', k: 'vertical line heavy quote' },
      { c: '▏', k: 'vertical bar thin quote' },
    ],
  },
];

const ALL = SYMBOL_GROUPS.flatMap((g) => g.items.map((i) => ({ ...i, group: g.id })));

/** Deduplicated keyword search; empty query shows the category browser instead. */
export function searchSymbols(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  const seen = new Set();
  return ALL.filter((item) => {
    if (seen.has(item.c)) return false;
    if (!terms.every((t) => item.k.includes(t) || item.c === t)) return false;
    seen.add(item.c);
    return true;
  });
}

export const SYMBOL_COUNT = new Set(ALL.map((i) => i.c)).size;
